# Generated by Django 6.0.6 on 2026-06-11 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('politicas_publicas', models.JSONField(default=list)),
                ('cant_provincias', models.IntegerField()),
                ('robos_promedio', models.FloatField()),
                ('recuperos_promedio', models.FloatField()),
                ('tasa_recupero_promedio', models.FloatField()),
                ('prioridad_promedio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='KpiNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robos_totales', models.IntegerField()),
                ('recuperos_totales', models.IntegerField()),
                ('tasa_recupero_promedio', models.FloatField()),
                ('tasa_robo_nacional', models.FloatField()),
                ('max_prioridad_provincia', models.CharField(max_length=100)),
                ('min_prioridad_provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MetricaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algoritmo', models.CharField(max_length=255)),
                ('k_clusters', models.IntegerField()),
                ('inercia', models.FloatField()),
                ('coeficiente_silueta', models.FloatField()),
                ('features_utilizadas', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('poblacion', models.IntegerField()),
                ('robos_totales', models.IntegerField()),
                ('recuperos_totales', models.IntegerField()),
                ('tasa_robo', models.FloatField()),
                ('tasa_robo_log', models.FloatField()),
                ('tasa_recupero', models.FloatField()),
                ('tasa_recupero_smoothed', models.FloatField()),
                ('anio_modelo_promedio', models.FloatField()),
                ('edad_titular_promedio', models.FloatField()),
                ('marca_lider_robo', models.CharField(max_length=100)),
                ('porcentaje_nacional', models.FloatField()),
                ('prioridad_visual', models.FloatField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='api.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='ProvinciaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=6)),
                ('robos', models.IntegerField()),
                ('recuperos', models.IntegerField()),
                ('tasa_recupero', models.FloatField()),
                ('tasa_recupero_smoothed', models.FloatField()),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='api.provincia')),
            ],
            options={
                'ordering': ['periodo'],
                'unique_together': {('provincia', 'periodo')},
            },
        ),
    ]
