# Generated by Django 6.0.6 on 2026-06-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDnrpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite_tipo', models.CharField(max_length=255)),
                ('tramite_fecha', models.DateField()),
                ('fecha_inscripcion_inicial', models.DateField(blank=True, null=True)),
                ('registro_seccional_codigo', models.IntegerField()),
                ('registro_seccional_descripcion', models.CharField(max_length=255)),
                ('registro_seccional_provincia', models.CharField(db_index=True, max_length=100)),
                ('automotor_origen', models.CharField(max_length=100)),
                ('automotor_anio_modelo', models.IntegerField()),
                ('automotor_tipo_codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('automotor_tipo_descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('automotor_marca_codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('automotor_marca_descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('automotor_modelo_codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('automotor_modelo_descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('automotor_uso_codigo', models.IntegerField(blank=True, null=True)),
                ('automotor_uso_descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('titular_tipo_persona', models.CharField(blank=True, max_length=100, null=True)),
                ('titular_domicilio_localidad', models.CharField(blank=True, max_length=255, null=True)),
                ('titular_domicilio_provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('titular_genero', models.CharField(blank=True, max_length=50, null=True)),
                ('titular_anio_nacimiento', models.IntegerField(blank=True, null=True)),
                ('titular_pais_nacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('titular_porcentaje_titularidad', models.FloatField(blank=True, null=True)),
                ('tramite_anio', models.IntegerField(db_index=True)),
                ('tramite_mes', models.IntegerField()),
                ('tramite_periodo', models.CharField(db_index=True, max_length=6)),
            ],
        ),
    ]
