# Generated by Django 6.0.6 on 2026-06-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registrodnrpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provincia',
            name='porcentaje_nacional',
        ),
    ]
